services:
  postgres:
    image: postgres:latest
    container_name: turnos_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: TurnosAppDb
    ports:
      - "5432:5432"
    networks:
      - turnos_net
    volumes:
      - postgres_data:/var/lib/postgresql   # 👈 corregido, sin /data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TurnosAppDb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  api_turnos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turnos_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=TurnosAppDb;Username=postgres;Password=Password123"
    ports:
      - "8080:8080"
    networks:
      - turnos_net

  frontend:
    build:
      context: ./turnos-app-frontend
      dockerfile: Dockerfile
    container_name: turnos_frontend
    depends_on:
      - api_turnos
    environment:
      VITE_API_BASE_URL: "http://localhost:8080/api"
    ports:
      - "5173:80"
    networks:
      - turnos_net

networks:
  turnos_net:
    driver: bridge

volumes:
  postgres_data:
    name: turnos_postgres_data