// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurnosApp.Infra.Data.Context;

#nullable disable

namespace TurnosApp.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260802172608_AgregarGraciaSuscripcionPastDue")]
    partial class AgregarGraciaSuscripcionPastDue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.AdelantoProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LiquidacionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.HasIndex("RecursoId");

                    b.HasIndex("TenantId");

                    b.ToTable("AdelantosProfesional", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DatosEspecificosJson")
                        .HasColumnType("text")
                        .HasColumnName("DatosEspecificosJson");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenConfirmacionEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TokenConfirmacionExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetPassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenResetPasswordExpira")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasFilter("\"PasswordHash\" IS NOT NULL AND \"Email\" IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Cobro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreMetodoPagoSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PorcentajeComisionSnapshot")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PorcentajeModificadorSnapshot")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoModificadorSnapshot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TurnoId");

                    b.ToTable("Cobros", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.HorarioAtencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecursoId", "DiaSemana");

                    b.ToTable("HorariosAtencion", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PeriodoDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodoHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioPagoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("UsuarioPagoId");

                    b.HasIndex("TenantId", "RecursoId", "PeriodoDesde", "PeriodoHasta")
                        .IsUnique();

                    b.ToTable("Liquidaciones", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.LiquidacionDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioBaseAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoComisionSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorComisionSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TurnoId");

                    b.ToTable("LiquidacionDetalles", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.ListaEspera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NotificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecursoId", "Estado");

                    b.ToTable("ListasEspera", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsEfectivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PorcentajeModificador")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoModificador")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MetodosPago", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.MovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CobroId")
                        .HasColumnType("integer");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsEfectivoSnapshot")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MetodoPagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("MovimientoOrigenId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreMetodoPagoSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SesionCajaId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CobroId");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("MovimientoOrigenId");

                    b.HasIndex("SesionCajaId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosCaja", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CuerpoHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DestinatarioEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("EnviadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IntentosEnvio")
                        .HasColumnType("integer");

                    b.Property<int?>("ListaEsperaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProgramadaPara")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReclamadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReclamadaPorRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ListaEsperaId");

                    b.HasIndex("ReclamadaPorRunId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EstadoEnvio", "ProgramadaPara");

                    b.HasIndex("TurnoId", "EstadoEnvio");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("TrialDias")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("\"UsuarioId\" IS NOT NULL");

                    b.ToTable("Recursos", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.ReglaComision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("TenantId", "RecursoId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true AND \"ServicioId\" IS NULL");

                    b.HasIndex("TenantId", "RecursoId", "ServicioId")
                        .IsUnique()
                        .HasFilter("\"Activo\" = true AND \"ServicioId\" IS NOT NULL");

                    b.ToTable("ReglasComision", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("PermisosMask")
                        .HasColumnType("bigint");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Servicios", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.SesionCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CierreForzado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MontoFinalDeclarado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MontoInicial")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("\"Estado\" = 'Abierta'");

                    b.HasIndex("UsuarioAperturaId");

                    b.HasIndex("UsuarioCierreId");

                    b.ToTable("SesionesCaja", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsGrandfathered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("EstadoSuscripcion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Trial");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FrecuenciaLiquidacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Mensual");

                    b.Property<string>("MercadoPagoPreapprovalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("PastDueDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PermiteReservasPublicas")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteSolapamiento")
                        .HasColumnType("boolean");

                    b.Property<int?>("PlanId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("SuscripcionVenceEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TenantId");

                    b.HasIndex("RecursoId", "FechaHoraInicio")
                        .HasDatabaseName("IX_Turnos_Recurso_FechaHoraInicio");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.TurnoServicio", b =>
                {
                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioAplicado")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("TurnoId", "ServicioId");

                    b.HasIndex("ServicioId");

                    b.ToTable("TurnoServicios", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OnboardingCompletado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TokenConfirmacionEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TokenConfirmacionExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenResetPassword")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenResetPasswordExpira")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("TenantId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NotificacionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("NotificacionId")
                        .IsUnique();

                    b.ToTable("WebhookEvents", (string)null);
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.AdelantoProfesional", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Adelantos")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany("AdelantosProfesional")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("AdelantosProfesional")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");

                    b.Navigation("Recurso");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Clientes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Cobro", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany("Cobros")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Cobros")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Turno", "Turno")
                        .WithMany("Cobros")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.HorarioAtencion", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Liquidacion", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Liquidaciones")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Usuario", "UsuarioPago")
                        .WithMany()
                        .HasForeignKey("UsuarioPagoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Recurso");

                    b.Navigation("Tenant");

                    b.Navigation("UsuarioPago");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.LiquidacionDetalle", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Liquidacion", "Liquidacion")
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Turno", "Turno")
                        .WithMany("LiquidacionDetalles")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Liquidacion");

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.ListaEspera", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Recurso");

                    b.Navigation("Servicio");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.MetodoPago", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("MetodosPago")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.MovimientoCaja", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Cobro", "Cobro")
                        .WithMany()
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TurnosApp.Core.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TurnosApp.Core.Domain.Entities.MovimientoCaja", "MovimientoOrigen")
                        .WithMany()
                        .HasForeignKey("MovimientoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurnosApp.Core.Domain.Entities.SesionCaja", "SesionCaja")
                        .WithMany("Movimientos")
                        .HasForeignKey("SesionCajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cobro");

                    b.Navigation("MetodoPago");

                    b.Navigation("MovimientoOrigen");

                    b.Navigation("SesionCaja");

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurnosApp.Core.Domain.Entities.ListaEspera", "ListaEspera")
                        .WithMany()
                        .HasForeignKey("ListaEsperaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("ListaEspera");

                    b.Navigation("Tenant");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Recurso", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Recursos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.ReglaComision", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany("ReglasComision")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany("ReglasComision")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ReglasComision")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Servicio");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Rol", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Servicio", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Servicios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.SesionCaja", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("SesionesCaja")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Usuario", "UsuarioApertura")
                        .WithMany()
                        .HasForeignKey("UsuarioAperturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Usuario", "UsuarioCierre")
                        .WithMany()
                        .HasForeignKey("UsuarioCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");

                    b.Navigation("UsuarioApertura");

                    b.Navigation("UsuarioCierre");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Plan", "Plan")
                        .WithMany("Tenants")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Turno", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Recurso", "Recurso")
                        .WithMany("Turnos")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Turnos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Recurso");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.TurnoServicio", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Servicio", "Servicio")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Turno", "Turno")
                        .WithMany("TurnoServicios")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("TurnosApp.Core.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosApp.Core.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Liquidacion", b =>
                {
                    b.Navigation("Adelantos");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.MetodoPago", b =>
                {
                    b.Navigation("Cobros");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Recurso", b =>
                {
                    b.Navigation("AdelantosProfesional");

                    b.Navigation("Liquidaciones");

                    b.Navigation("ReglasComision");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Servicio", b =>
                {
                    b.Navigation("ReglasComision");

                    b.Navigation("TurnoServicios");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.SesionCaja", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("AdelantosProfesional");

                    b.Navigation("Clientes");

                    b.Navigation("Cobros");

                    b.Navigation("Liquidaciones");

                    b.Navigation("MetodosPago");

                    b.Navigation("MovimientosCaja");

                    b.Navigation("Recursos");

                    b.Navigation("ReglasComision");

                    b.Navigation("Servicios");

                    b.Navigation("SesionesCaja");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosApp.Core.Domain.Entities.Turno", b =>
                {
                    b.Navigation("Cobros");

                    b.Navigation("LiquidacionDetalles");

                    b.Navigation("TurnoServicios");
                });
#pragma warning restore 612, 618
        }
    }
}
